services:
  question-service:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: question-service-prod
    restart: unless-stopped
    ports:
      - '4010:4010'
    environment:
      - NODE_ENV=production
      - PORT=4010
      - DATABASE_URL=mongodb://question-service-db:27017/questions_db
      - BACKEND_BASE_URL=${BACKEND_BASE_URL}
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db

  db:
    image: mongo:8.0
    container_name: question-service-db
    ports:
      - '4011:27017'
    volumes:
      - question-service-db-data:/data/db
      - ./src/database/init:/docker-entrypoint-initdb.d

  redis:
    image: redis:8-alpine
    container_name: question-service-redis
    restart: unless-stopped
    ports:
      - '4012:6379'
    volumes:
      - question-service-redis-data:/data

volumes:
  question_service-db-data:
  question-service-redis-data:
