apiVersion: apps/v1
kind: Deployment
metadata:
  name: communication-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: communication-service
  template:
    metadata:
      labels:
        app: communication-service
    spec:
      containers:
        - name: communication-service
          image: asia-southeast1-docker.pkg.dev/peerprep-g26-2025/peerprep/communication-service:latest
          ports:
            - containerPort: 4070
